- hosts: k8sMaster
  become: yes
  tasks:
    - name: initialize the cluster with standard Calicol subnet
      shell: kubeadm init --pod-network-cidr=192.168.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: cansible
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to cansible user home inside kube folder config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/cansible/.kube/config
        remote_src: yes
        owner: cansible

    - name: install Pod network
      become: yes
      become_user: cansible
      shell: kubectl apply -f https://docs.projectcalico.org/v3.11/manifests/calico.yaml >> calico_pod_network_setup.txt
      args:
        chdir: $HOME
        creates: calico_pod_network_setup.txt



  





        
