---
- hosts: client1 client2 client3 client4 client5 client6 client7 client8
  remote_user: ansible
  become: yes
  become_method: sudo

  tasks:
  - name : restart pm2 all
    command: 'pm2 restart all'
    become: yes
    become_user: connect
